name: CI_CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install
    
    - name: Clear cache
      run: npm cache clean --force

    - name: Build the project
      run: npm run build

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm run test:e2e

    - name: Copy files to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist $EC2_USER@$EC2_HOST:~/app

    - name: Deploy on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/app/NestJs-Hello-World-App
            git pull origin main  # Assuming you're deploying from 'main' branch
            npm install
            npm audit fix
            npm run build
            pm2 stop all || true
            pm2 start dist/main.js
          EOF
      
